// Work out skill tags for every library score and write them to catalog-skills.js, so the library can filter by
// skill without parsing 3,883 scores at page load. Run after changing any catalog or skillTags(): node scripts/build-skills.cjs
const fs = require('node:fs'),
  path = require('node:path'),
  vm = require('node:vm');
const root = path.join(__dirname, '..');
function buildSkills() {
  const context = {console};
  vm.createContext(context);
  for (const f of [
    'vendor/abcjs-basic-min.js',
    'catalog.js',
    'catalog-expanded.js',
    'catalog-licensed.js',
    'score-tools.js'
  ])
    vm.runInContext(fs.readFileSync(path.join(root, f), 'utf8'), context);
  const out = {};
  const catalog = vm.runInContext('catalog', context),
    tag = vm.runInContext('abc=>skillMask(skillTags(ABCJS.parseOnly(abc)[0]))', context);
  for (const score of catalog) out[score.id] = tag(score.abc);
  return out;
}
const render = skills =>
  '// Generated by scripts/build-skills.cjs from the catalog and skillTags(); do not edit by hand. Each value is a bit mask over SKILLS.\nconst catalogSkills=' +
  JSON.stringify(skills) +
  ';\n';
module.exports = {buildSkills, render};
if (require.main === module) {
  const skills = buildSkills();
  fs.writeFileSync(path.join(root, 'catalog-skills.js'), render(skills));
  console.log(`catalog-skills.js: ${Object.keys(skills).length} scores tagged`);
}
